site_name: "Basic Formal Ontology"
repo_url: https://github.com/johnbeve/hub-and-spoke/
edit_uri: '?query=root/hub-and-spoke/docs/'
theme:
  name: material
  palette:
    primary: 'black'
nav:
  - Basic Formal Ontology: index.md
  - Introduction: introduction.md
  - Scope: scope.md
  - Conformance: conformance.md
  - Conventions: conventions.md
  - Terms and Definitions: terms-and-definitions.md
  - BFO-Core: bfo-core.md
  - Temporalized Relations: temporal-extensions.md
  - Users and Applications: users-and-applications.md
  - Summary: summary.md